const list = [
  {
    id: 1,
    title: "Banana",
    price: 70,
    img: "./banana.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "Apple",
    price: 120,
    img: "./apple.jpeg",
    amount: 1,
  },
  {
    id: 3,
    title: "Mango",
    price: 50,
    img: "./mango.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Kiwi",
    price: 40,
    img: "./kiwi.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "Orange",
    price: 60,
    img: "./orange.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "Tomato",
    price: 80,
    img: "./tomato.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Cabbage",
    price: 25,
    img: "./cabbage.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Potato",
    price: 30,
    img: "./potato.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Carrot",
    price: 50,
    img: "./carrot.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Onion",
    price: 30,
    img: "./onion.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Saffron",
    price: 205,
    img: "./saffron.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Turmeric",
    price: 110,
    img: "./turmeric.jpg",
    amount: 1,
  },
  {
    id: 13,
    title: "Black Salt",
    price: 150,
    img: "./blacksalt.jpg",
    amount: 1,
  },
  {
    id: 14,
    title: "Cardamom",
    price: 3300,
    img: "./cardamon.jpg",
    amount: 1,
  },
  {
    id: 15,
    title: "Clove ",
    price: 1700,
    img: "./clove.jpg",
    amount: 1,
  },
  
];

export default list;